#!/usr/bin/env bash
# Multiplies 2 numbers gotten from user

read -p "Enter first number: " num1
read -p "Enter second number: " num2

product="$((num1 * num2))"

echo "The product of $num1 and $num2 is $product"

